name: FB Marketplace Monitor

on:
  schedule:
    - cron: "*/10 * * * *"  # 每10分钟运行一次
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

       - name: Create fb_cookies.json from secret
        run: |
          echo "${{ secrets.FB_COOKIES_JSON }}" > fb_cookies.json


      - name: Run monitor script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python marketplace_monitor.py
